-- PROBLEM 1
drop table product;
CREATE TABLE PRODUCT 
(PRODUCT_ID NUMBER(8) PRIMARY KEY,
PRODUCT_NAME VARCHAR2(20));

set feedback on;
set serveroutput on;
DECLARE
  TYPE LIST_OF_PRODUCTS IS TABLE OF PRODUCT.PRODUCT_NAME%TYPE
    INDEX BY PLS_INTEGER;
  
  PRODUCTS LIST_OF_PRODUCTS;
  ROW_INDEX PLS_INTEGER;
BEGIN
  PRODUCTS (2)  := 'Bleach';
  PRODUCTS (12) := 'Corona wipes';
  PRODUCTS (33) := 'Paper Plates';
  PRODUCTS (74) := 'Food Jar';
  PRODUCTS (56) := 'Scrap Metal';

  ROW_INDEX := PRODUCTS.FIRST;
  
  WHILE(ROW_INDEX IS NOT NULL)
  LOOP
    DBMS_OUTPUT.PUT_LINE(PRODUCTS(ROW_INDEX));
    ROW_INDEX := PRODUCTS.NEXT(ROW_INDEX);
  END LOOP;
END;


-- PROBLEM 2
SELECT * FROM DONOR;
SELECT IDDONOR, FIRSTNAME, LASTNAME
  FROM DONOR;

set feedback on;
set serveroutput on;
DECLARE
  -- DECLARE DONOR TYPE
  TYPE DONOR_T IS RECORD
  (IDDONOR  DONOR.IDDONOR%TYPE,
  FIRSTNAME DONOR.FIRSTNAME%TYPE,
  LASTNAME  DONOR.LASTNAME%TYPE);
  -- GET DONOR DATA
  CURSOR DONOR_CUR IS
    SELECT DONOR.IDDONOR, DONOR.FIRSTNAME, DONOR.LASTNAME
      FROM DONOR; 
  -- ARRAY TYPE
  TYPE LIST_OF_DONORS IS TABLE OF DONOR_T
      INDEX BY PLS_INTEGER;
  -- DECLARE ARRAY
  DONOR_lIST LIST_OF_DONORS;
  ROW_INDEX PLS_INTEGER := 0;
BEGIN
  -- FILL ARRAY
  FOR DONOR_REC IN DONOR_CUR
  LOOP
    -- PUT RECORD DATA INTO ARRAY
    DONOR_lIST (ROW_INDEX)  := DONOR_REC;
    -- INCREMENT INDEX
    ROW_INDEX := ROW_INDEX + 1;
  END LOOP;
  -- PRINT ARRAY
  FOR INDX IN DONOR_lIST.FIRST .. DONOR_lIST.LAST
  LOOP
    DBMS_OUTPUT.PUT_LINE('------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Donor ID is: ' || DONOR_lIST(INDX).IDDONOR);
    DBMS_OUTPUT.PUT_LINE('First Name is: ' || DONOR_lIST(INDX).FIRSTNAME);
    DBMS_OUTPUT.PUT_LINE('Last Name is: ' || DONOR_lIST(INDX).LASTNAME);
  END LOOP;
END;