-- PROBLEM 1
CREATE OR REPLACE PROCEDURE CALC_COMMISSION
(SALES_AMOUNT_IN IN NUMBER,
COMMISSION OUT NUMBER)
IS
  NO_SALES EXCEPTION;
  NEGATIVE_SALES EXCEPTION;
  NULL_SALES EXCEPTION;
BEGIN
  IF SALES_AMOUNT_IN = 0 THEN
    COMMISSION := 0;
    RAISE NO_SALES;
  ELSIF SALES_AMOUNT_IN < 0 THEN
    COMMISSION := 0;
    RAISE NEGATIVE_SALES;
  ELSIF SALES_AMOUNT_IN = NULL THEN
    COMMISSION := 0;
    RAISE NULL_SALES;
  ELSE
    COMMISSION := SALES_AMOUNT_IN * 0.1;
  END IF;
EXCEPTION  
  WHEN NO_SALES THEN
    DBMS_OUTPUT.PUT_LINE('SALES VALUE WAS EQUIVALENT TO ZERO');
  WHEN NEGATIVE_SALES THEN
    DBMS_OUTPUT.PUT_LINE('SALES VALUE WAS NEGATIVE');
  WHEN NULL_SALES THEN
    DBMS_OUTPUT.PUT_LINE('SALES VALUE WAS NULL');  
END;  

-- TESTING
set feedback on;
set serveroutput on;
DECLARE
  NULL_SALES NUMBER;
  NEGATIVE_SALES NUMBER := -1;
  ZERO_SALES NUMBER := 0;
  ZERO_RESULT NUMBER;
  NEGATIVE_RESULT NUMBER;
  NULL_RESULT NUMBER;
BEGIN
  CALC_COMMISSION(NEGATIVE_SALES, NEGATIVE_RESULT);
  CALC_COMMISSION(ZERO_SALES, ZERO_RESULT);
  CALC_COMMISSION(NULL_SALES, NULL_RESULT);
  DBMS_OUTPUT.PUT_LINE('RESULT FROM CALCULATING NEGATIVE COMMISSION WAS ' || NEGATIVE_RESULT);
  DBMS_OUTPUT.PUT_LINE('RESULT FROM CALCULATING ZERO COMMISSION WAS '     || ZERO_RESULT);
  DBMS_OUTPUT.PUT_LINE('RESULT FROM CALCULATING NULL COMMISSION WAS '     || NULL_RESULT);
END;


-- PROBLEM 2
drop procedure CALC_COMMISSION;
CREATE OR REPLACE PROCEDURE CALC_COMMISSION
(SALES_AMOUNT_IN IN NUMBER,
COMMISSION_PERCENT IN NUMBER,
COMMISSION OUT NUMBER)
IS
  NO_SALES EXCEPTION;
  NEGATIVE_SALES EXCEPTION;
  NULL_SALES EXCEPTION;
  NEGATIVE_COMMISSION EXCEPTION;
  SALES_COMMISSION NUMBER;
BEGIN
  IF SALES_AMOUNT_IN = 0 THEN
    COMMISSION := 0;
    RAISE NO_SALES;
  ELSIF SALES_AMOUNT_IN < 0 THEN
    COMMISSION := 0;
    RAISE NEGATIVE_SALES;
  ELSIF SALES_AMOUNT_IN IS NULL THEN
    COMMISSION := 0;
    RAISE NULL_SALES;
  ELSE
    SALES_COMMISSION := SALES_AMOUNT_IN * (COMMISSION_PERCENT * 100);
    IF SALES_COMMISSION < 0 THEN
      COMMISSION := 0;
      RAISE NEGATIVE_COMMISSION;
    ELSE
      COMMISSION := SALES_COMMISSION;
    END IF;  
  END IF;
EXCEPTION  
  WHEN NO_SALES THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: SALES VALUE WAS EQUIVALENT TO ZERO');
  WHEN NEGATIVE_SALES THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: SALES VALUE WAS NEGATIVE');
  WHEN NULL_SALES THEN
    DBMS_OUTPUT.PUT_LINE('ERROR: SALES VALUE WAS NULL');  
  WHEN NEGATIVE_COMMISSION THEN 
    DBMS_OUTPUT.PUT_LINE('ERROR: SALES COMMISSION WAS NEGATIVE');  
END;  

-- TESTING
set feedback on;
set serveroutput on;
DECLARE
  NULL_SALES NUMBER;
  NULL_RESULT NUMBER;
  
  ZERO_SALES NUMBER := 0;
  ZERO_RESULT NUMBER;
  
  NEGATIVE_SALES NUMBER := -1;
  NEGATIVE_RESULT NUMBER;
  
  POSITIVE_COMMISSION_RATE NUMBER := 20;
  NEGATIVE_COMMISSION_RATE NUMBER := -20;
  NEGATIVE_COMMISSION_RESULT NUMBER;
BEGIN
  CALC_COMMISSION(4, NEGATIVE_COMMISSION_RATE, NEGATIVE_COMMISSION_RESULT);
  DBMS_OUTPUT.PUT_LINE('RESULT FROM CALCULATING NEGATIVE COMMISSION RATE WAS ' || NEGATIVE_COMMISSION_RESULT);
  CALC_COMMISSION(NEGATIVE_SALES, POSITIVE_COMMISSION_RATE, NEGATIVE_RESULT);
  DBMS_OUTPUT.PUT_LINE('RESULT FROM CALCULATING NEGATIVE SALES WAS ' || NEGATIVE_RESULT);
  CALC_COMMISSION(ZERO_SALES, POSITIVE_COMMISSION_RATE, ZERO_RESULT);
  DBMS_OUTPUT.PUT_LINE('RESULT FROM CALCULATING ZERO COMMISSION WAS '     || ZERO_RESULT);
  CALC_COMMISSION(NULL_SALES, POSITIVE_COMMISSION_RATE, NULL_RESULT);
  DBMS_OUTPUT.PUT_LINE('RESULT FROM CALCULATING NULL COMMISSION WAS '     || NULL_RESULT);
END;







